#import profiler
print("\nNote: this script requires the hogprof environment\n")
import argparse
import pandas as pd
import h5py
import os
from pyoma.browser import db
import pyoma.browser.models as db_models
import sys
import pickle
from time import time
from datetime import datetime
import traceback
import numpy as np
import seaborn as sns


from ete3 import NCBITaxa
ncbi = NCBITaxa()

### get current time
start_time_secs = time() 
start_time = datetime.fromtimestamp(start_time_secs).strftime('%Y-%m-%d %H:%M:%S')
### print start time human readable
print(f"Script started at: {start_time}\n")

def add_profiler_path(profiler_path):
    """Add the directory containing profiler.py to Python's sys.path"""
    if not os.path.exists(profiler_path):
        raise FileNotFoundError(f"Profiler path does not exist: {profiler_path}")
    profiler_dir = os.path.dirname(os.path.abspath(profiler_path))
    if profiler_dir not in sys.path:
        sys.path.append(profiler_dir)

def create_directory(dirpath):
    if not os.path.exists(dirpath):
        os.mkdir(dirpath)
    return dirpath

def get_hashes(subhogs_table, fam2orthoxml_file):
    subhogs_df = pd.read_csv(subhogs_table, sep='\t', index_col=0)
    if 'hashid' in subhogs_df.columns:
        return subhogs_table
    print(f"Extracting hashes from file: {fam2orthoxml_file}")
    subhogs_df.index.name = 'subhogid'
    ### read in the fam2orthoxml table generated by HogProf lshbuilder and the tree file 
    fam2orthoxml_df = pd.read_csv(fam2orthoxml_file)
    # build mapping: subhog_id -> hash row index
    subhog_to_hashid = {subhog: idx for idx, subhog in enumerate(fam2orthoxml_df['subhog_id'])}
    # attach hash ids
    subhogs_df['hashid'] = subhogs_df.index.map(subhog_to_hashid)
    # outputqueryfile
    outputqueryfile = subhogs_table.replace(".tsv","_queries.tsv")
    # save new file with hash ids
    subhogs_df.to_csv(outputqueryfile, sep='\t')
    return outputqueryfile

'''use hashes directly to extract hits'''
def extract_hits_from_hashes(lshforestpath, hashes_h5, treepath, outputfile, profiler_path,
                                   allvsall, k, subhogs_table, thresholds_df):
    
    # Add profiler directory to path and import
    add_profiler_path(profiler_path)
    import profiler

    subhogs_df = pd.read_csv(subhogs_table, sep='\t', index_col=0)
    ## index label is subhogid
    subhogs_df.index.name = 'subhogid'
    #print(subhogs_df.head())
    #subhogs_df.set_index('subhogid')
    subhog_to_hashid = subhogs_df['hashid'].to_dict()
    hashid_to_subhog = {v: k for k, v in subhog_to_hashid.items()}
    #subhog_to_taxon = subhogs_df['taxon_name'].to_dict()
    
    print("\nBuilding the profiler")
    p = profiler.Profiler(lshforestpath = lshforestpath, 
                        hashes_h5= hashes_h5, 
                        oma = False , 
                        nsamples = 256 ,
                        mastertree = treepath,
                        slicesubhogs = True
                        )
    
    #print(p.subhogname_to_fam_dict)

    p.slicesubhogs = False ### setting as False to try original hogid2fam function in profiler.py
    #print("slicesubhogs:",p.slicesubhogs)
    print("Pulling hashes...")
    raw_profiles = p.pull_hashes(subhog_to_hashid.values()) # returns hashid to hashsig dict

    ### here check that the expected number of hashes was pulled
    if len(raw_profiles)!= len(hashid_to_subhog):
        print("Warning! Could not pull all the hashes!")
    subhogs_without_hash = []
    for subhog, hashid in subhog_to_hashid.items():
        if hashid not in raw_profiles.keys():
            subhogs_without_hash.append(subhog)
    if len(subhogs_without_hash)>0:
        print("Examples:", subhogs_without_hash[:5])

    profiles = {
        hashid_to_subhog[h]: {
            'hashsig': raw_profiles[h],
            'hashid': h
        }
        for h in raw_profiles
        if h in hashid_to_subhog
    }

    profiles_df = pd.DataFrame.from_dict(profiles, orient='index')
    profiles_num = len(profiles_df.index.unique())
    #print(f'Got hash signatures for {len(profiles.index.unique())} HOGs')
    #print(profiles.head())

    ### checking for empty / degenerate /invalid signatures
    profiles_df['sigsum'] = profiles_df.hashsig.map(lambda x : np.sum(x.digest()))
    profiles_df = profiles_df[profiles_df.sigsum>0]
    #print(f'{len(profiles.index.unique())} HOGs have valid signatures')
    if profiles_num != len(profiles_df.index.unique()):
        print("Warning: invalid hash signatures detected!")

    def get_candidates(p, query_sig, k):
        # query LSH forest for candidate hash ids - get top k
        candidate_subhogids = [target_hog[target_hog.find('_')+1:] for target_hog in p.lshobj.query(query_sig, k)]
        candidate_hashids = [p.subhog_to_hashids_dict[target_hog] for target_hog in candidate_subhogids]
        local_hashid_to_subhog = {int(h): s for h, s in zip(candidate_hashids, candidate_subhogids)}
        # pull candidate signatures (dict: hashid -> MinHash)
        candidate_hashes = p.pull_hashes(candidate_hashids)
        return candidate_hashids, local_hashid_to_subhog, candidate_hashes
    
    def get_scores(candidate_hashids,candidate_hashes, query_sig, level_threshold):
        scores = {}
        for hashid in candidate_hashids: ### candidate_hashids are the closest but they are not ordered
            sig = candidate_hashes[hashid]
            this_score = sig.jaccard(query_sig)
            if this_score >= level_threshold:
                scores[hashid] = this_score
        return scores

    ### get jaccard scores too
    rows = []
    counter = 0
    no_hits_subhogs = []
    ### data structure_for all_vs_all
    taxa_networks_dict = {}
    network_id_to_hid = {}
    level_to_T_dict = {}
    print("Querying each HOG...")
    for query_subhog_id, querydict in profiles.items():
        ### clean hogids e.g. 14_HOG:0004777_537 where 14 is the internal taxid (bin in thresholds) 
        # and 537 is the internal hog id from the orthoxml transversal
        query_level = int(query_subhog_id.split("_")[0])
        hog_id_str = query_subhog_id.split("_")[1]
        try:
            level_threshold = thresholds_df['empirical_t'].loc[query_level]
        except:
            level_threshold = 0 ### take everything if no T is specified
            print(f"Warning: no T defined for {query_level}")
        level_to_T_dict[query_level] = level_threshold
        current_taxon = thresholds_df['taxname'].loc[query_level]
        query_sig = querydict['hashsig']
        query_hashid = querydict['hashid']
        # query LSH forest for candidate hash ids - get top k
        candidate_hashids, local_hashid_to_subhog, candidate_hashes = get_candidates(p, query_sig, k)

        scores = get_scores(candidate_hashids,candidate_hashes, query_sig, level_threshold)
        ### it is possible that none pass the threshold
        if len(scores) == 0:
            no_hits_subhogs.append(query_subhog_id)
            continue
        ### it is also possible that all pass the threshold, so we need to check more (only check once more with double k)
        if len(scores) == len(candidate_hashids):
            candidate_hashids, local_hashid_to_subhog, candidate_hashes = get_candidates(p, query_sig, 2*k)
            scores = get_scores(candidate_hashids,candidate_hashes, query_sig, level_threshold)

        # sort candidate scores descending
        scored_pairs = sorted(scores.items(), key=lambda x: x[1], reverse=True)

        # save info for allvsall
        if allvsall:
            if query_level not in taxa_networks_dict.keys():
                network_id_to_hid = {}
            else:
                network_id_to_hid = taxa_networks_dict[query_level]
            # add new info
            network_id_to_hid[query_subhog_id] = query_hashid
            taxa_networks_dict[query_level] = network_id_to_hid

        # build rows: one row per query-target pair
        for hid, jaccard in scored_pairs:
            target_subhog = local_hashid_to_subhog[hid]

            # target_subhog expected like "14_HOG:0004777_537" or "14_751313"
            target_hog_clean = target_subhog  # already in desired form
            try:
                target_level = int(target_hog_clean.split("_")[0])
            except Exception:
                # if parsing fails, skip
                print(f"Warning: cannot parse level from {target_hog_clean}; skipping")
                continue
            try:
                target_hog_id_str = target_hog_clean.split("_")[1]
            except Exception:
                target_hog_id_str = ""

            # don't keep self hits:
            if query_subhog_id ==target_hog_clean:
                continue

            # only keep same-level hits so threshold makes sense
            if target_level != query_level:
                continue

            # flag same-family (compare the id string parts)
            same_fam = (hog_id_str == target_hog_id_str)

            # append row
            rows.append({
                'query_hog': query_subhog_id,
                'target_hog': target_hog_clean,
                'jaccard': jaccard,
                'empirical_t': level_threshold,
                'taxname': current_taxon,
                'same_fam': same_fam
            })
    
    taxa_hsig_dict ={}
    ### change info for allvsall
    if allvsall:
        for level, network_id_to_hid in taxa_networks_dict.items():
            all_raw_profiles = p.pull_hashes(network_id_to_hid.values()) # returns hashid to hashsig dict
            ### turn into subhog to hashsig
            network_id_to_hsig = {subhogid:all_raw_profiles[hid] for subhogid, hid in  network_id_to_hid.items()}
            taxa_hsig_dict[level] = [level_to_T_dict[level],network_id_to_hsig]

    hits_df = pd.DataFrame(rows)
    print(hits_df.head())

    if len(no_hits_subhogs)>0:
        print(f"No hits found for {len(no_hits_subhogs)} subHOGs")
        print("Examples:", no_hits_subhogs[:5])
    
    ### save to file
    hits_df.to_csv(outputfile, index=False)
    print("Created file:", outputfile)

    return taxa_hsig_dict

### from Dave's jupyter notebook, with changes
def compare_all_vs_all(taxa_hsig_dict, outputfile):
    print("Performing all vs all comparison...")
    for level, [level_T, network_id_to_hsig] in taxa_hsig_dict.items():
        out_eps = outputfile.replace(".csv",f"{level}.eps")
        ids = list(network_id_to_hsig.keys())
        sigs = [network_id_to_hsig[i] for i in ids]
        #jkern = [[sig1.jaccard(sig2) if (i != j and sig1.jaccard(sig2)>level_T) else 0 for j, sig2 in enumerate(sigs)] for i, sig1 in enumerate(sigs)]
        jkern = np.array([
            [sig1.jaccard(sig2) if i != j else 0
            for j, sig2 in enumerate(sigs)]
            for i, sig1 in enumerate(sigs)
        ])
        # convert to distance for clustering
        dist = 1 - jkern
        ### now apply threshold
        jkern_plot = jkern.copy()
        jkern_plot[jkern_plot < level_T] = 0
        print(jkern)
        #g = sns.clustermap(jkern, xticklabels=ids, yticklabels=ids, figsize=(20, 20), vmin=0, vmax=1)
        g = sns.clustermap(
            dist,
            xticklabels=ids,
            yticklabels=ids,
            figsize=(20, 20),
            cmap="viridis_r"  # reversed so small distance = high similarity
        )
        g.savefig(out_eps, format='eps')
        print(f"Created file: {out_eps}")

def compare_all_vs_all(taxa_hsig_dict, outputfile):
    print("Performing all vs all comparison (untested)...")
    for level, [level_T, network_id_to_hsig] in taxa_hsig_dict.items():
        out_eps = outputfile.replace(".csv", f"{level}.eps")
        ids = list(network_id_to_hsig.keys())
        if len(ids) < 2:
            print(f"Skipping {level}: only {len(ids)} profile(s)")
            continue
        sigs = [network_id_to_hsig[i] for i in ids]
        # similarity matrix
        jkern = np.array([
            [sig1.jaccard(sig2) for sig2 in sigs]
            for sig1 in sigs
        ])
        np.fill_diagonal(jkern, 1.0)
        # distance for clustering
        dist = 1 - jkern
        # --- threshold ONLY for display ---
        jkern_plot = jkern.copy()
        jkern_plot[jkern_plot < level_T] = 0
        g = sns.clustermap(
            dist,
            xticklabels=ids,
            yticklabels=ids,
            figsize=(20, 20),
            cmap="viridis_r"
        )
        g.savefig(out_eps, format='eps')
        print(f"Created file: {out_eps}")

def main(lshforestpath, hashes_h5, treepath, outputfile, profiler_path, queries_file,thresholds_file,
         allvsall = False, k= 1000):
    ### print arguments
    print("\n📋 Running with the following parameters:")
    print(f"  • LSH Forest path: {lshforestpath}")
    print(f"  • Hashes HDF5: {hashes_h5}")
    print(f"  • Tree path: {treepath}")
    print(f"  • Output file: {outputfile}")
    print(f"  • Profiler path: {profiler_path}")
    print(f"  • Queries file: {queries_file}")
    print(f"  • All vs all: {allvsall}")
    print(f"  • k: {k}")
    print(f"  • thresholds table: {thresholds_file}")
    print("\n")

    ### if thresholds are given, take them into account
    thresholds_df = pd.read_csv(thresholds_file)[['bin','empirical_t','taxname']]
    thresholds_df.set_index('bin', inplace=True)

    create_directory(os.path.dirname(outputfile))

    ### get hits from hashes
    taxa_hsig_dict = extract_hits_from_hashes(lshforestpath, hashes_h5, treepath, outputfile, profiler_path,
                                              allvsall, k, queries_file, thresholds_df)
    if allvsall:
        compare_all_vs_all(taxa_hsig_dict, outputfile=outputfile.replace(".csv", "_allvsall.csv"))


## Command line argument parsing'''
def parse_args():
    """
    Parse command line arguments.
    """
    print("Parsing command line arguments")
    parser = argparse.ArgumentParser(description="Extract hits from the profiler for levels mode, per taxon. Queries are subHOGs that can be found in the fam2orthoxml file.")
    parser.add_argument("-i", "--input", required=False, help="Folder containing the output of HogProf LSHbuilder. Expected files:"
    " newlshforest.pkl hashes.h5 reformatted_tree.nwk fam2orthoxml.csv profilersavingpath.csv",
    default="/home/agavriil/curnagl_mount/venom_project/2a_hogprof_testing/levels_fastoma_metazoa_251114_subhogs_eventlim1_260619/")
    parser.add_argument("-o", "--outputfile", required=False, help="Output csv file with extracted hits.",
    default="/home/agavriil/curnagl_mount/venom_project/3_hogprof_hits/levels_fastoma_metazoa_251114_subhogs_eventlim1_260619_venomexpression_blastphits/extracted_hits_from_subhogs_local.csv")
    parser.add_argument("--allvsall",help="Run all vs all mode additionally to the main hit extraction (may take a long time).", 
                        default=True)
    parser.add_argument("--k", type=int, default=1000, help="Number of top hits to extract for each query.")
    parser.add_argument("--queries_file", type=str, help="Table of HOGs to use as queries (e.g. venom HOGs table). 1st column is subhogid and a hashid column needs to exist." \
    " Make sure to include blastp in the filename if it is a blastp output file.",
    default="/home/agavriil/curnagl_mount/venom_project/3_hogprof_hits/levels_fastoma_metazoa_251114_subhogs_eventlim1_260619_queries/venomhog_full_subhog_metadata_venomqueries.tsv")
    parser.add_argument("--thresholds", help="Table of thresholds for each taxonomic level (csv).",
    default="/home/agavriil/curnagl_mount/venom_project/3a_hogprof_thresholds/levels_fastoma_metazoa_251114_subhogs_eventlim1_260619_thresholds/bins_jaccard_thresholds.csv")
    parser.add_argument("--profilerpath", help="Full path to profiler.py script of HogProf (to be used if run from another location).",
    default="profiler.py")
    return parser.parse_args()


if __name__ == "__main__":
    # Parse command line arguments
    args = parse_args()
    #print("Are arguments fixed?")
    inputfolder = args.input
    lshforestpath = inputfolder + "newlshforest.pkl"
    hashes_h5 = inputfolder + "hashes.h5"
    treepath = inputfolder + "speciestree.nwk"
    treepath = inputfolder + "reformatted_tree.nwk"
    fam2orthoxml_file = inputfolder + "fam2orthoxml.csv"
    queries_file = args.queries_file

    # special case for unknown hashids (subhogid per line, identical to fam2orthoxml)
    queries_file = get_hashes(queries_file, fam2orthoxml_file)

    # Run the main function with the parsed arguments
    main(
        lshforestpath=lshforestpath,
        hashes_h5=hashes_h5,
        treepath=treepath,
        outputfile=args.outputfile,
        profiler_path = args.profilerpath,
        allvsall=args.allvsall,
        k=args.k,
        queries_file = queries_file,
        thresholds_file=args.thresholds
    )

### print end time
end_time_secs = time()
end_time = datetime.fromtimestamp(end_time_secs).strftime('%Y-%m-%d %H:%M:%S')
print(f"Script finished at: {end_time}\n")
execution_time = end_time_secs - start_time_secs
### print execution time but reformat it to be human readable
print(f"Total execution time: {round(execution_time, 2)} seconds\n")
print("\nDONE!\n")