[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "HogProf"
version = "0.0.11"
authors = [
  { name = "Dave Moi", email = "dmoi@unil.ch" },
]
dependencies = [
  "biopython",
  "datasketch",
  "ete3",
  "goatools",
  "h5py",
  "legacy-cgi; python_version >= '3.13'", # ete3 imports the removed cgi package
  "lxml",
  "numpy",
  "pandas",
  "pyham>=1.1.10",
  "pyoma",
  "tables",
  "tqdm",
]
description = "Phylogenetic Profiling with OMA and minhashing"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[project.urls]
"Homepage" = "https://github.com/DessimozLab/HogProf"
"Bug Tracker" = "https://github.com/DessimozLab/HogProf/issues"
"Docs" = "https://dessimozlab.github.io/HogProf/"

[project.scripts]
lshbuilder = "hogprof.lshbuilder:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
